_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}
max_epochs: 10
precision: bf16-mixed
check_val_every_n_epoch: 1
enable_model_summary: false

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

strategy: ddp_find_unused_parameters_true
